# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class OnCustomGamepadChangedEvent(object):
    """ [客户端] 当自定义手柄按键绑定发生改变时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def name(self):
        # type: () -> str
        """ 按键名称 """
        return self.mArgs.get("name")

    @property
    def oldKey(self):
        # type: () -> str
        """ 旧的键码 """
        return self.mArgs.get("oldKey")

    @property
    def newKey(self):
        # type: () -> str
        """ 新的键码 """
        return self.mArgs.get("newKey")

class OnCustomGamepadPressInGame(object):
    """ [客户端] 当玩家按下自定义手柄按键时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def name(self):
        # type: () -> str
        """ 按键名称 """
        return self.mArgs.get("name")

    @property
    def key(self):
        # type: () -> str
        """ 键码 """
        return self.mArgs.get("key")

    @property
    def category(self):
        # type: () -> str
        """ 按键分类 """
        return self.mArgs.get("category")

    @property
    def isDown(self):
        # type: () -> str
        """ 按下状态 ("1"为按下, "0"为抬起)，仅普通按键有效 """
        return self.mArgs.get("isDown")

    @property
    def magnitude(self):
        # type: () -> float
        """ 扳机力度 (0.0-1.0)，仅扳机键有效 """
        return self.mArgs.get("magnitude")

    @property
    def x(self):
        # type: () -> float
        """ 摇杆X轴偏移 (-1.0-1.0)，仅摇杆键有效 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> float
        """ 摇杆Y轴偏移 (-1.0-1.0)，仅摇杆键有效 """
        return self.mArgs.get("y")

    @property
    def screenName(self):
        # type: () -> str
        """ 当前屏幕名称 """
        return self.mArgs.get("screenName")

class OnCustomKeyChangedEvent(object):
    """ [客户端] 当自定义按键绑定发生改变时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def name(self):
        # type: () -> str
        """ 按键名称 """
        return self.mArgs.get("name")

    @property
    def oldKey(self):
        # type: () -> str
        """ 旧的键码 """
        return self.mArgs.get("oldKey")

    @property
    def newKey(self):
        # type: () -> str
        """ 新的键码 """
        return self.mArgs.get("newKey")

class OnCustomKeyPressInGame(object):
    """ [客户端] 当玩家按下自定义按键时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def name(self):
        # type: () -> str
        """ 按键名称 """
        return self.mArgs.get("name")

    @property
    def key(self):
        # type: () -> str
        """ 键码 """
        return self.mArgs.get("key")

    @property
    def category(self):
        # type: () -> str
        """ 按键分类 """
        return self.mArgs.get("category")

    @property
    def isDown(self):
        # type: () -> str
        """ 按下状态 ("1"为按下, "0"为抬起) """
        return self.mArgs.get("isDown")

    @property
    def screenName(self):
        # type: () -> str
        """ 当前屏幕名称 """
        return self.mArgs.get("screenName")
