# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class PhysxTouchClientEvent(object):
    """ [客户端] 给自定义刚体添加的碰撞体，与其他碰撞体或原版实体发生碰撞/结束碰撞时触发。需要在碰撞体创建时使用PxEventMask.Client才会触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def touch(self):
        # type: () -> list[dict]
        """ 开始接触的碰撞体对的信息。一个碰撞体在创建时使用了PxEventMask.Found，他与其他碰撞体/原版实体开始接触时，会出现在列表中 """
        return self.mArgs.get("touch")

    @property
    def lost(self):
        # type: () -> list[dict]
        """ 结束接触的碰撞体对的信息。一个碰撞体在创建时使用了PxEventMask.Lost，他与其他碰撞体/原版实体结束接触时，会出现在列表中 """
        return self.mArgs.get("lost")

class PhysxTouchServerEvent(object):
    """ [服务端] 给自定义刚体添加的碰撞体，与其他碰撞体或原版实体发生碰撞/结束碰撞时触发。需要在碰撞体创建时使用PxEventMask.Server才会触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def touch(self):
        # type: () -> list[dict]
        """ 开始接触的碰撞体对的信息。一个碰撞体在创建时使用了PxEventMask.Found，他与其他碰撞体/原版实体开始接触时，会出现在列表中 """
        return self.mArgs.get("touch")

    @property
    def lost(self):
        # type: () -> list[dict]
        """ 结束接触的碰撞体对的信息。一个碰撞体在创建时使用了PxEventMask.Lost，他与其他碰撞体/原版实体结束接触时，会出现在列表中 """
        return self.mArgs.get("lost")

class PhysxTriggerClientEvent(object):
    """ [客户端] 给自定义刚体添加的触发器，与其他碰撞体或原版实体进入/离开触发器时触发。需要在触发器创建时使用PxEventMask.Client才会触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def found(self):
        # type: () -> list[dict]
        """ 进入触发器的碰撞体对的信息。它与其他碰撞体/原版实体进入触发器时，会出现在列表中 """
        return self.mArgs.get("found")

    @property
    def lost(self):
        # type: () -> list[dict]
        """ 离开触发器的碰撞体对的信息。它与其他碰撞体/原版实体离开触发器时，会出现在列表中 """
        return self.mArgs.get("lost")

class PhysxTriggerServerEvent(object):
    """ [服务端] 给自定义刚体添加的触发器，与其他碰撞体或原版实体发生进入触发器/离开触发器时触发。需要在触发器创建时使用PxEventMask.Server才会触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def found(self):
        # type: () -> list[dict]
        """ 进入触发器的碰撞体对的信息。一个碰撞体在创建时使用了PxEventMask.Found，它与其他碰撞体/原版实体进入触发器时，会出现在列表中 """
        return self.mArgs.get("found")

    @property
    def lost(self):
        # type: () -> list[dict]
        """ 离开触发器的碰撞体对的信息。一个碰撞体在创建时使用了PxEventMask.Lost，它与其他碰撞体/原版实体离开触发器时，会出现在列表中 """
        return self.mArgs.get("lost")
